### ISSUE TITLE
When I run it the first time the application breaks

### ISSUE THREAD

**Issue by danielmelogpi** [conradoqg/cryptocoinwatch#1]
When I run the application on a clean environment I get the following error:

```
➜   ./cryptocoinwatch-0.5.0-x86_64.AppImage                     
installed: X-AppImage-BuildId=93f96100-8d9f-11a7-369f-f9ee2234fc48 image: X-AppImage-BuildId=93f96100-8d9f-11a7-369f-f9ee2234fc48
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Initializing...
Environment: production
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/daniel/.config/Cryptocoin Watch/settings.yaml.txt'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at SettingsStore.load (/tmp/.mount_PRnMw5/usr/bin/resources/app.asar/src/settingsStore.js:30:51)
    at new SettingsStore (/tmp/.mount_PRnMw5/usr/bin/resources/app.asar/src/settingsStore.js:21:14)
    at Object.<anonymous> (/tmp/.mount_PRnMw5/usr/bin/resources/app.asar/src/main.js:33:23)
    at Object.<anonymous> (/tmp/.mount_PRnMw5/usr/bin/resources/app.asar/src/main.js:280:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

When running again the application starts normaly

**Comment by conradoqg** [comment]
I just fixed it on bd639fe170f6d6653b12ecedf47f3f9e8fb784ac, I also generated the [v0.5.1](https://github.com/conradoqg/cryptocoinwatch/releases/tag/v0.5.1) release.
